# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  assimp_config = debug
  ImGui_config = debug
  yaml_cpp_config = debug
  EnTT_config = debug
  Razor_config = debug
  Edge_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  assimp_config = release
  ImGui_config = release
  yaml_cpp_config = release
  EnTT_config = release
  Razor_config = release
  Edge_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  assimp_config = dist
  ImGui_config = dist
  yaml_cpp_config = dist
  EnTT_config = dist
  Razor_config = dist
  Edge_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW assimp ImGui yaml-cpp EnTT Razor Edge Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Edge EnTT GLFW ImGui Razor Sandbox assimp yaml-cpp

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Razor/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

assimp:
ifneq (,$(assimp_config))
	@echo "==== Building assimp ($(assimp_config)) ===="
	@${MAKE} --no-print-directory -C Razor/vendor/assimp -f Makefile config=$(assimp_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Razor/vendor/ImGui -f Makefile config=$(ImGui_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Razor/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

EnTT:
ifneq (,$(EnTT_config))
	@echo "==== Building EnTT ($(EnTT_config)) ===="
	@${MAKE} --no-print-directory -C Razor/vendor/entt -f Makefile config=$(EnTT_config)
endif

Razor: GLFW assimp ImGui yaml-cpp
ifneq (,$(Razor_config))
	@echo "==== Building Razor ($(Razor_config)) ===="
	@${MAKE} --no-print-directory -C Razor -f Makefile config=$(Razor_config)
endif

Edge: Razor
ifneq (,$(Edge_config))
	@echo "==== Building Edge ($(Edge_config)) ===="
	@${MAKE} --no-print-directory -C Edge -f Makefile config=$(Edge_config)
endif

Sandbox: Razor
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Razor/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Razor/vendor/assimp -f Makefile clean
	@${MAKE} --no-print-directory -C Razor/vendor/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C Razor/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C Razor/vendor/entt -f Makefile clean
	@${MAKE} --no-print-directory -C Razor -f Makefile clean
	@${MAKE} --no-print-directory -C Edge -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   assimp"
	@echo "   ImGui"
	@echo "   yaml-cpp"
	@echo "   EnTT"
	@echo "   Razor"
	@echo "   Edge"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"