<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>Binaries</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Razor-ScriptBridge/Razor-ScriptBridge.csproj" />
  </ItemGroup>
</Project>
