<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Dist</Configurations>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>..\Edge\Resources\Scripts\</OutputPath>
    <IntermediateOutputPath>..\Edge\Resources\Scripts\Intermediates\Debug\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>..\Edge\Resources\Scripts\</OutputPath>
    <IntermediateOutputPath>..\Edge\Resources\Scripts\Intermediates\Release\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Dist|x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>..\Edge\Resources\Scripts\</OutputPath>
    <IntermediateOutputPath>..\Edge\Resources\Scripts\Intermediates\Dist\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Dist|x64' ">
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Source\Razor\Collision.cs" />
    <Compile Include="Source\Razor\Component.cs" />
    <Compile Include="Source\Razor\Entity.cs" />
    <Compile Include="Source\Razor\Input.cs" />
    <Compile Include="Source\Razor\InternalCalls.cs" />
    <Compile Include="Source\Razor\Log.cs" />
    <Compile Include="Source\Razor\Scene.cs" />
    <Compile Include="Source\Razor\System.cs" />
    <Compile Include="Source\Razor\Transform.cs" />
  </ItemGroup>
</Project>